### PR TITLE
Move alert up to not hide guesses

### PR DESCRIPTION
**Pull request by gbear605**
Currently the alert displays partly over the first guess, hiding what the guess was. This can be frustrating if the alert was about that guess, such as the guess not being long enough or not being a word. This moves it up so that it fully covers the top bar and does not cover any of the guesses.

### CODE REVIEW

**Comment by gbear605** [comment]
Before the change:
Before Change

After the change:
After Change

**Comment by hannahcode** [comment]
This looks good - the only issue is that we changed the losing alert to persist, which with this change would cover the title and info and stats buttons. Maybe we can add margin to the very top of the app and have the alerts show above?

**Comment by gbear605** [comment]
Good idea! I've moved the app down a bit so that the alerts don't cover up anything

**Comment by hannahcode** [comment]
Great, thanks!

**Pull request merged**
