### PR TITLE
Fix #53: Open Stats and Info Modals Center

### LINKED ISSUE #53: Modals should open in the middle of the view
The bottom and top of the view, especially on mobile, is often occluded by notifications, toasts, status bars, etc and therefore modals should open near the middle of the view to be most accessible.

### PR DESCRIPTION
**Pull request by buddhist-uni**
This asks the two primary modals to align their contents in the center of the screen, instead of at the bottom of it.

### CODE REVIEW

**Comment by hannahcode** [comment]
I just merged a PR for refactoring the modals, so there are conflicts here now - would you mind pulling down the current version and making these changes?

**Comment by buddhist-uni** [comment]
Rebased 👍

**Comment by hannahcode** [comment]
Thanks!

**Comment by hannahcode** [comment]
Ah - so sorry, I didn't see your rebase until I made some additional changes, so it looks like we still have conflicts. I'm going to stop making changes for the evening feel free to update this again whenever you have a moment.

**Comment by buddhist-uni** [comment]
Oops! I think I am bad at git... What did I just do?

**Comment by buddhist-uni** [comment]
Oh! It seems that your latest change was on top of mine, so you merged this in already.  Thanks! :)

**Comment by hannahcode** [comment]
Oh whoops! I must have been confused. Thanks again :)

**Pull request closed without merging**
